### PR TITLE
Add basic filter test for layout resource

### PR DESCRIPTION
**Pull request by bofalke**
Ref #113 

First Test for the Layout Resource filter.

### CODE REVIEW

**Comment by bofalke** [comment]
Is this going in the right direction? I guess all i am missing now for the layout component are the different scenarios

- [ ] Filtering by uiComponent
- [ ] Order by createdAt
- [ ] Order by Reference

**Comment by silverbackdan** [comment]
This looks good thanks.
May I suggest we have 2 scenarios?
1 which will test the layouts endpoint and another which checks that it can be filtered instead of merging both tests into 1?
Would you still like to have some Docker configs?

**Comment by bofalke** [comment]
Yes i can split it into 2 scenarios 👍 

The docker config would be helpful for manual playing around but i think i can add the test cases mentioned above without. So no need to rush it.

**Comment by silverbackdan** [comment]
Sorry for the delay, I'll be working on the docker configs now, see what I can get going.
If you need to run this repo you could always run the template repository, and map this bundle to your local machine in the composer.json file in the api directory - this way you'll be running everything - full stack with mercure, caddy, varnish etc.

**Comment by silverbackdan** [comment]
Hi @bofalke - sorry I've been extremely tied up with Antoine and many mercure updates and other fixes which I'm continuing to work on today actually - I think I've just finished my last update to `main` branch. Hopefully it won't require a rebase but if so, you should be fine to do this any time from now I hope as I'm moving onto front-end work.

**Comment by bofalke** [comment]
Sorry for the delay, i was a little busy the last weeks. However i think i finally managed to include all the tests for the layout component. The GitGuardian Security Check occured after i merged the main branch, i guess i will try and rebase it

**Comment by silverbackdan** [comment]
The gitguardian is OK, it's a dummy secret but looks real so I think I just need to make it look like a dummy :)

**Comment by silverbackdan** [comment]
These are very good tests thank you for your work on it. I'm happy to merge when you are finished and I can easily duplicate these tests for the page resource as well with these layout resource tests in place.
LMK when you're finished your side and I'll merge.

**Comment by silverbackdan** [comment]
Also lowest dependencies tests will fail for now until APIP core 3.0.3 is released. I didn't want the fixme statement in there and we will require that as the minimum dependency.

**Comment by bofalke** [comment]
Okay it is green now as i removed the merge commit by rebasing onto the main branch. However Scrutinizer fails during composer install, anything i need to do here?

**Comment by silverbackdan** [comment]
Nah that's all good, thanks - merging now.
Thanks very much for the PR - really appreciated. I'll try remember the tool I used to list contributors and get you into the readme soon.

**Comment by bofalke** [comment]
Cool thanks!

I try to add some tests for the other components as well

**Comment by silverbackdan** [comment]
Amazing, thank you!

**Pull request merged**
